#!/bin/sh

# run php lint on all modified & added files
for file in `git status -s -uno |grep "^\s*[AM]" | awk '{ print $2 }'`;
do
	ext="${file##*.}"
	if [ "$ext" == "php" ]; then
		/usr/bin/env php -l $file;
	fi
done
