#!/bin/bash
set -e

abspath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
abspath=`dirname "$abspath"`

if [ ! -d ~/bin ]; then
	echo -n "Path ~/bin not found, do you want to create it? (y|n):"
	read -n1 answer
	if [ "$answer" == "y" ]; then
		echo -e "\n"
		mkdir ~/bin
	else
		echo -e "\nAborting..."
		exit
	fi
fi

for file in $abspath/*
do

	file=${file##*/}
	if [ "$file" != "README.md" ] && [ "$file" != "link2bin" ]; then

		fullcmdpath=~/bin/$file
		if [ -f $fullcmdpath ]; then
			echo "File $fullcmdpath already exists, skipping..."
		else
			ln -s $abspath/$file $fullcmdpath
		fi

	fi

done